config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  root to: 'boards#index'

  authenticate :admin_user do
    mount Flipper::UI.app(Flipper) => '/flipper'
  end

  resources :boards do
    resources :columns, only: %i[edit create update destroy] do
      resources :cards, only: %i[edit create update destroy]
    end
  end

  resources :gallery, only: %i[index] do
    post :images, on: :collection
  end

  resources :posts, only: %i[new create show edit update index destroy]

  devise_scope :user do
    authenticated :user do
      root to: 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/column.rb
# == Schema Information
#
# Table name: columns
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :bigint
#
# Indexes
#
#  index_columns_on_board_id  (board_id)
#
class Column < ApplicationRecord
  belongs_to :board
  has_many :cards, -> { order(position: :asc) }, dependent: :destroy,
                                                 inverse_of: :column

  validates :name, presence: true
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  before_action :set_column, only: %i[edit update destroy]

  def edit; end

  def create
    column = Column.create!(column_params)
    redirect_to board_path(column.board)
  end

  def update
    @column.update!(column_params)
    redirect_to board_path(@column.board)
  end

  def destroy
    @column.destroy!
    redirect_to board_path(@column.board)
  end

  private

  def set_column
    @column = Column.find(params[:id])
  end

  def column_params
    params.require(:column).permit(:name, :board_id)
  end
end

app/views/columns/_column.html.erb
  <div class='column'>
    <%= link_to '', board_column_path(board_id: board_id, id: column.id), class: 'column__delete', method: :delete, data: {confirm: 'Are you sure?'} %>
    <%= turbo_frame_tag dom_id column do %>
      <div class='column__title'>
        <%= link_to column.name, edit_board_column_path(board_id: board_id, id: column.id) %>
      </div>
    <% end %>
    <div class='column__body' data-controller="trello" data-trello-column-id-value="<%= column.id%>">
      <%= render partial: 'cards/card', collection: column.cards, locals: { board_id: column.board.id, column_id: column.id } %>
      <div>
        <%= render partial: 'cards/form',
                   locals: {
                      klass: 'hidden',
                      card: Card.new(column_id: column.id),
                      url: board_column_cards_path(board_id: board_id, column_id: column.id)
                    }
        %>
      </div>
    </div>
    <%= render partial: 'cards/form',
               locals: {
                  klass: 'p-4',
                  card: Card.new(column_id: column.id),
                  url: board_column_cards_path(board_id: board_id, column_id: column.id)
               }
    %>
  </div>

app/views/columns/_form.html.erb
<%= form_with(model: column, url: url, class: klass) do |form| %>
  <%= form.text_field :name, placeholder: 'Write a new column...', class: 'column__title column__title--input' %>
  <%= form.number_field :board_id, class: 'hidden' %>

  <%= form.submit 'Send', class: 'column__submit hidden'%>
<% end %>

app/views/columns/edit.html.erb
<%= turbo_frame_tag dom_id @column do %>
  <%= render 'form', column: @column, klass: '', url: board_column_path(board_id: @column.board_id, id: @column.id)%>
<% end %>