config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  root to: 'boards#index'

  authenticate :admin_user do
    mount Flipper::UI.app(Flipper) => '/flipper'
  end

  resources :boards do
    resources :columns, only: %i[edit create update destroy] do
      resources :cards, only: %i[edit create update destroy]
    end
  end

  resources :gallery, only: %i[index] do
    post :images, on: :collection
  end

  resources :posts, only: %i[new create show edit update index destroy]

  devise_scope :user do
    authenticated :user do
      root to: 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/card.rb
# == Schema Information
#
# Table name: cards
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  position   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  column_id  :bigint
#
# Indexes
#
#  index_cards_on_column_id  (column_id)
#
class Card < ApplicationRecord
  belongs_to :column
  acts_as_list scope: :column

  validates :name, presence: true

  delegate :board, to: :column
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i[edit update destroy]

  def edit; end

  def create
    card = Card.create!(card_params)
    redirect_to board_path(card.board)
  end

  def update
    @card.update!(card_params)
    redirect_to board_path(@card.board)
  end

  def destroy
    @card.destroy!
    redirect_to board_path(@card.board)
  end

  private

  def set_card
    @card = Card.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:name, :position, :column_id)
  end
end

app/views/cards/_card.html.erb
<div class='card' id="<%= dom_id card %>" data-position='<%= card.position %>' data-id="<%= card.id %>" data-new-card='false'>
    <%= link_to '', board_column_card_path(board_id: board_id, column_id: column_id, id: card.id), class: 'card__delete', method: :delete, data: {confirm: 'Are you sure?'}%>
    <div class='card__header'>
      <div class='card__title'>
      <%= turbo_frame_tag dom_id card do %>
        <%= link_to card.name, edit_board_column_card_path(board_id: board_id, column_id: column_id, id: card.id), data: {turbo_frame: dom_id(card)}%>
      <%end%>
      </div>
    </div>
    <%= render 'cards/form', card: card, klass: 'hidden', url: board_column_card_path(board_id: board_id, column_id: column_id, id: card.id) %>
</div>

app/views/cards/_form.html.erb
<%= form_with(model: card, url: url, class: klass) do |form| %>
  <%= form.text_field :name, placeholder: 'Write a new card...', id: 'js-name-value', class: 'card__title card__title--input' %>
  <%= form.number_field :position, id: 'js-position-value', class: 'hidden' %>
  <%= form.number_field :column_id, id: 'js-column-id', class: 'hidden' %>

  <%= form.submit 'Send', class: 'card__submit js-card__submit hidden'%>
<% end %>

app/views/cards/edit.html.erb
<%= turbo_frame_tag dom_id @card do %>
  <%= render 'form', card: @card, klass: '', url: board_column_card_path(board_id: @card.board.id, column_id: @card.column_id, id: @card.id)%>
<% end %>