config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  root to: 'boards#index'

  authenticate :admin_user do
    mount Flipper::UI.app(Flipper) => '/flipper'
  end

  resources :boards do
    resources :columns, only: %i[edit create update destroy] do
      resources :cards, only: %i[edit create update destroy]
    end
  end

  resources :gallery, only: %i[index] do
    post :images, on: :collection
  end

  resources :posts, only: %i[new create show edit update index destroy]

  devise_scope :user do
    authenticated :user do
      root to: 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  body       :text             not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_posts_on_title  (title)
#
class Post < ApplicationRecord
  validates :title, :body, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include Pagy::Backend

  def index
    @page_number = params[:page].present? ? params[:page].to_i : 1
    @pagy_posts, @posts = pagy(Post.order(:id), page: @page_number, items: 3)
    @pagy_next_posts, @next_posts = pagy(Post.order(:id), page: @page_number + 1, items: 3)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    Post.find(params[:id]).destroy!

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <%= render 'shared/error_messages', resource: post %>

  <%= render(FieldComponent.new(:title, form: form, placeholder: 'Title', required: true)) %>
  <%= render(FieldComponent.new(:body, form: form, placeholder: 'Body', required: true)) %>

  <div class='actions'>
    <%= render(ButtonComponent.new(text: "#{action_name} Post")) %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class='flex mt-5 font-bold text-2xl'>
  <%= post.title %>
</div>

<div class='flex mt-5'>
  <%= post.body %>
</div>

app/views/posts/edit.html.erb
<h2 class='title'>Editing Post</h2>

<%= render 'form', post: @post, action_name: 'Update' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class='title'>Posts</h2>

<%= link_to new_post_path, class: 'w-full flex' do %>
  <%= render(ButtonComponent.new(text: 'New Post')) %>
<% end %>

<hr class='my-5'>

<% if @posts.any? %>
  <div data-controller='scroll_to_top'>
    <%= turbo_frame_tag dom_id(@posts.first) do %>
      <div data-controller="infinite-scroll" data-infinite-scroll-path-value="<%= posts_path(page: @page_number) %>" data-infinite-scroll-target="entry">
        <% @posts.each do |post| %>
          <div class='mt-5'>
            <%= render post %>

            <div class='flex flex-row'>
              <%= link_to post_path(post), data: { turbo_frame: "_top" } do %>
                <%= render(ButtonComponent.new(text: 'View', css_class: 'mt-2 mb-5 w-16')) %>
              <% end %>
              <%= link_to edit_post_path(post), data: { turbo_frame: "_top" } do %>
                <%= render(ButtonComponent.new(text: 'Edit', css_class: 'mt-2 mb-5 ml-2 w-16')) %>
              <% end %>
              <%= link_to post_path(post), method: :delete, data: { turbo_frame: "_top", confirm: 'Are you sure?' } do %>
                <%= render(ButtonComponent.new(text: 'Destroy', css_class: 'mt-2 mb-5 ml-2 w-16')) %>
              <% end %>
            </div>
          </div>

          <hr class='my-1'>
        <% end %>
      </div>
      <%= turbo_frame_tag dom_id(@next_posts.first), loading: :lazy, src: posts_path(page: @page_number + 1) if @next_posts.present? %>
    <% end %>

    <div>
      <%= render(ButtonComponent.new(text: 'Back to top', css_class: 'mt-2 mb-5 w-16', data: { action: 'click->scroll_to_top#scrollToTop' })) %>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<h2 class='title'>New Post</h2>

<%= render 'form', post: @post, action_name: 'Create' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= render @post %>

<div class='flex flex-row'>
  <%= link_to edit_post_path(@post), data: { turbo_frame: "_top" } do %>
    <%= render(ButtonComponent.new(text: 'Edit', css_class: 'mt-2 mb-5 w-16')) %>
  <% end %>
  <%= link_to posts_path, data: { turbo_frame: "_top" } do %>
    <%= render(ButtonComponent.new(text: 'Back', css_class: 'mt-2 mb-5 ml-2 w-16')) %>
  <% end %>
</div>